### ISSUE TITLE
Ruby 3.2 unrecognized option: max_redirects

### ISSUE THREAD

**Issue by CAMOBAP** [janko/down#82] opened 2023-02-13 11:57 UTC
The gem works perfectly for 2.7, 3.0, and 3.1, but fails for ruby 3.2 with:
```
ArgumentError:
 unrecognized option: max_redirects
# ./vendor/bundle/ruby/3.2.0/gems/down-5.4.0/lib/down/net_http.rb:145:in `open_uri'
# ./vendor/bundle/ruby/3.2.0/gems/down-5.4.0/lib/down/net_http.rb:94:in `download'
# ./vendor/bundle/ruby/3.2.0/gems/down-5.4.0/lib/down/backend.rb:13:in `download'
# ./vendor/bundle/ruby/3.2.0/gems/down-5.4.0/lib/down.rb:10:in `download'
```

For code:
```
Down.download(
  url,
  open_timeout: 10,
  read_timeout: 10,
  max_redirects: 10,
  headers: headers,
  content_length_proc: ->(content_length) {
    progress_bar.total = content_length if content_length
  },
  progress_proc: -> (progress) {
    progress_bar.increment(progress)
  }
)
```

**Comment by janko** [comment] 2023-02-13 15:10
I couldn't reproduce this, for me the script below runs successfully on Ruby 3.2.0:

```rb
require "down"

Down.download(
  "https://upload.wikimedia.org/wikipedia/commons/3/3c/Salto_del_Angel-Canaima-Venezuela08.JPG",
  open_timeout: 10,
  read_timeout: 10,
  max_redirects: 10,
  headers: {},
  content_length_proc: ->(content_length) {},
  progress_proc: -> (progress) {},
)
```

Would you mind posting a self-contained example that reproduces the issue?

**Comment by janko** [comment] 2023-02-21 14:34
Since I wasn't able to reproduce the error from the original code, I will close this for now.

**Closed by janko** 2023-02-21 14:34 UTC

**Comment by CAMOBAP** [comment] 2023-02-21 14:43
Sorry for ignore, I was able to reproduce it several times on CI, than the issue just gone
